# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 08:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 6, 26, 8, 53, 33, 689966, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
