# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 15:50
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contact_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannertranslation',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
