# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cart_session_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart item', 'verbose_name_plural': 'Cart items'},
        ),
        migrations.AlterField(
            model_name='order',
            name='client_name',
            field=models.CharField(default='', max_length=60, verbose_name='Client name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_unique_id',
            field=models.CharField(blank=True, editable=False, max_length=120, null=True, unique=True, verbose_name='Order Id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(verbose_name='Shipping address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'Available'), (1, 'Awaiting Payment'), (2, 'Payment completed'), (3, 'Cancelled'), (4, 'Delivered')], default=0),
        ),
    ]
