# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180623_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
    ]
