# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(to='products.Color'),
        ),
    ]
