# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180623_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, to='products.Color'),
        ),
    ]
