# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 09:07
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('1'), max_digits=10, null=True, verbose_name='Sale price'),
        ),
    ]
